# Generated by Django 3.2.7 on 2022-10-28 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFind', models.CharField(max_length=200)),
                ('infoFind', models.CharField(max_length=200)),
                ('genderFind', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('ubiFind', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePet', models.CharField(max_length=200)),
                ('infoPet', models.CharField(max_length=200)),
                ('agePet', models.DateField(blank=True, null=True)),
                ('typePet', models.CharField(max_length=200)),
                ('imgPet', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('genderPet', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passUsr', models.CharField(max_length=200)),
                ('ubiUsr', models.CharField(max_length=200)),
                ('mailUsr', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perdidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoLost', models.CharField(max_length=200)),
                ('dateLost', models.DateTimeField(blank=True, null=True)),
                ('ubiLost', models.CharField(blank=True, max_length=200)),
                ('petLost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ILMP_app.mascotas')),
            ],
        ),
        migrations.AddField(
            model_name='mascotas',
            name='usrPet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ILMP_app.usuarios'),
        ),
    ]
