# Generated by Django 3.2.7 on 2022-10-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILMP_app', '0003_encuentros_mascotas_perdidas_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('comunidadautonoma', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.RemoveField(
            model_name='encuentros',
            name='genderFind',
        ),
        migrations.RemoveField(
            model_name='encuentros',
            name='idFind',
        ),
        migrations.RemoveField(
            model_name='encuentros',
            name='ubiFind',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='datePet',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='genderPet',
        ),
        migrations.RemoveField(
            model_name='mascotas',
            name='idPet',
        ),
        migrations.RemoveField(
            model_name='perdidas',
            name='idLost',
        ),
        migrations.RemoveField(
            model_name='perdidas',
            name='ubiLost',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='agePet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perdidas',
            name='dateLost',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
