# Generated by Django 3.2.7 on 2022-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILMP_app', '0004_auto_20221010_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsr', models.CharField(max_length=200)),
                ('nameUsr', models.CharField(max_length=200)),
                ('passUsr', models.CharField(max_length=200)),
                ('ubiUsr', models.CharField(max_length=200)),
                ('mailUsr', models.CharField(max_length=200)),
                ('tlfUsr', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='agePet',
            field=models.DateField(blank=True, null=True),
        ),
    ]
