# Generated by Django 3.2.7 on 2022-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILMP_app', '0005_auto_20221010_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='tlfUsr',
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='imgPet',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='mailUsr',
            field=models.EmailField(max_length=254),
        ),
    ]
