# Generated by Django 3.2.7 on 2022-10-10 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ILMP_app', '0007_perdidas_petlost'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdidas',
            name='usrLost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ILMP_app.usuarios'),
        ),
    ]
