# Generated by Django 3.2.7 on 2022-10-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILMP_app', '0008_perdidas_usrlost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='idUsr',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='genderPet',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
