# Generated by Django 3.2.7 on 2022-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILMP_app', '0010_encuentros_genderfind'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentros',
            name='ubiFind',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perdidas',
            name='ubiLost',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
