# Generated by Django 3.2.7 on 2022-10-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ILMP_app', '0011_auto_20221013_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdidas',
            name='usrLost',
        ),
        migrations.AddField(
            model_name='mascotas',
            name='usrPet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ILMP_app.usuarios'),
        ),
    ]
