# Generated by Django 3.2.7 on 2022-10-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ILMP_app', '0012_auto_20221013_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perdidas',
            new_name='Perdidos',
        ),
    ]
